# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_stages: [commit]
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: detect-private-key
      - id: end-of-file-fixer
        verbose: true
      - id: check-yaml
      # - id: check-added-large-files
  # - repo: https://github.com/golangci/golangci-lint
  #   rev: v1.54.2
  #   hooks:
  #     - id: golangci-lint
  #       entry: golangci-lint run --new-from-rev HEAD
  #       language: golang
  #       always_run: false
  #       stages: [pre-commit]

  - repo: local
    hooks:
      - id: go-unit-tests
        name: run go test s(go test)
        language: system
        entry: go test -v ./...
        pass_filenames: false
        types: [go]
        stages: [pre-commit]
