apiVersion: apps/v1
kind: Deployment
metadata:
  name: group-0-prod-deployment
  namespace: group-0-prod
spec:
  selector:
    matchLabels:
      app: api
  replicas: 1
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: workshop-summer
#          image: ghcr.io/kkgo-software-engineering/workshop-summer:b363bea56839ebd2adf0f1bae2a36726e25ff810
          image: werockstar/workshop-summer:d3ef2f197cfeb226a0651ffa90d8b9823b51eada
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: "0.5"
              memory: 256Mi
