apiVersion: apps/v1
kind: Deployment
metadata:
  name: <GROUP_NO>-dev-deployment
  namespace: <GROUP_NO>-dev
spec:
  selector:
    matchLabels:
      app: api
  replicas: 1
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: workshop-summer
          image: ghcr.io/kkgo-software-engineering/workshop-summer:53f28cce6089c62c41f922d733166cb2bd3d9a64
          imagePullPolicy: Always
          env:
              -  name: DATABASE_POSTGRES_URI
                 valueFrom:
                    configMapKeyRef:
                        name: app-config
                        key: db.url
          livenessProbe:
            httpGet:
              path: /api/v1/health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /api/v1/health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: "0.5"
              memory: 256Mi
