apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: group-0-dev
spec:
  selector:
    matchLabels:
      app: api
  replicas: 1
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: workshop-summer
          image: ghcr.io/kkgo-software-engineering/workshop-summer:d772b0bdab900ab4aba2b89f1002677c633d44ba
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: "0.5"
              memory: 256Mi
