apiVersion: apps/v1
kind: Deployment
metadata:
  name: group-5-b1-dev-deployment
  namespace: group-5-b1-dev
spec:
  selector:
    matchLabels:
      app: api
  replicas: 1
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: workshop-summer-group-5-b1
          image: ghcr.io/kkgo-software-engineering/workshop-summer-group-5-b1:830ae203570de84570235441191f9385df10e319
          imagePullPolicy: Always
          env:
              -  name: DATABASE_POSTGRES_URI
                 valueFrom:
                     secretKeyRef:
                         key: db.url
                         name: secret
              -  name: SERVER_PORT
                 valueFrom:
                     configMapKeyRef:
                         name: app-config
                         key: server.port
              -  name: ENABLE_CREATE_SPENDER
                 valueFrom:
                     configMapKeyRef:
                         name: app-config
                         key: enable.create.spender
          livenessProbe:
            httpGet:
              path: /api/v1/health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /api/v1/health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 20
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: "0.5"
              memory: 256Mi
            requests:
                cpu: "0.25"
                memory: 128Mi
