apiVersion: v1
kind: Service
metadata:
  name: <GROUP_NO>-dev-service
  namespace: <GROUP_NO>-dev
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: api
  type: ClusterIP
