apiVersion: v1
kind: Service
metadata:
  name: group-0-dev-service
  namespace: group-0-dev
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: api
  type: ClusterIP
