name: Go CI

on:
    push:
        branches: [ main ]

jobs:
    build-and-push-docker-image:
        name: Build docker image and push to repositories
        runs-on: ubuntu-latest
        needs:
            - sonarqube
        steps:
            -   uses: actions/checkout@v4
            -   name: Setup SHA
                run: echo "GITHUB_SHA=${GITHUB_SHA}" >> $GITHUB_ENV

            -   name: Login ghcr.io
                uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
                with:
                    registry: ghcr.io
                    username: ${{ github.actor }}
                    password: ${{ secrets.GITHUB_TOKEN }}

            -   name: Build and push Docker image
                uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
                with:
                    push: ${{ github.ref == 'refs/heads/main' }}
                    tags: ghcr.io/${GITHUB_REPOSITORY}:${{ env.GITHUB_SHA }}

            -   name: Image digest
                run: echo ${{ steps.docker_build.outputs.digest }}
