name: Go CI

on:
    push:
        branches: [ main ]

jobs:
    build-and-push-docker-image:
        name: Build docker image and push to repositories
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v4
            -   name: Setup SHA
                run: echo "GITHUB_SHA=${GITHUB_SHA}" >> $GITHUB_ENV

            -   name: Login ghcr.io
                uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
                with:
                    registry: ghcr.io
                    username: ${{ github.actor }}
                    password: ${{ secrets.GITHUB_TOKEN }}

            -   name: Build and push Docker image
                uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
                with:
                    push: ${{ github.ref == 'refs/heads/main' }}
                    tags: ghcr.io/kkgo-software-engineering/workshop-summer:${{ env.GITHUB_SHA }}

            -   name: Image digest
                run: echo ${{ steps.docker_build.outputs.digest }}

    gitops-dev-versioning:
        runs-on: ubuntu-latest
        needs: build-and-push-docker-image
        steps:
            -   uses: actions/checkout@v4
                with:
                    fetch-depth: 0

            -   name: config git
                run: |
                    git --version
                    git config user.name "robot"
                    git config user.email "root@werockstar.dev"

            -   name: change image tag to deploy dev
                if: ${{ github.ref == 'refs/heads/main' }}
                run: |
                    sed -i -E "s/ghcr.io\/kkgo-software-engineering\/workshop-summer.*$/ghcr.io\/kkgo-software-engineering\/workshop-summer:${GITHUB_SHA}/" infra/gitops/dev/deployment.yml
                    git add infra/gitops/dev/deployment.yml
                    git commit -m "[skip actions] 🤖 change dev docker image version to ${GITHUB_SHA}"
                    git pull --rebase
                    git push

            -   name: change image tag to deploy hotfix
                if: ${{ github.ref == 'refs/heads/hotfix' }}
                run: |
                    sed -i -E "s/ghcr.io\/kkgo-software-engineering\/workshop-summer.*$/ghcr.io\/kkgo-software-engineering\/workshop-summer:${GITHUB_SHA}/" infra/gitops/hotfix/deployment.yml
                    git add infra/gitops/hotfix/deployment.yml
                    git commit -m "[skip actions] 🤖 change hotfix docker image version to ${GITHUB_SHA}"
                    git pull --rebase
                    git push

            -   name: set default docker image tag fot prd
                run: |
                    sed -i -E "s/default: .*/default: ${GITHUB_SHA}/" .github/workflows/prd-cd.yaml
                    git add .github/workflows/prd-cd.yaml
                    git commit -m "[skip actions] 🤖 change default docker tag"
                    git pull --rebase
                    git push
